# Generated by Django 5.0 on 2023-12-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijoz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companiya', models.CharField(max_length=200)),
                ('social', models.CharField(max_length=200)),
                ('otzv', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asoschi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('position', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='', verbose_name='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('position', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='', verbose_name='static/')),
            ],
        ),
    ]
